# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName:  'Build Stage'
  jobs:
 - jobs: Build
   displayName: 'Build job'
   steps:
   - task: NodeTool@0
   inputs:
     versionSpec: '14.x'
   displayName: 'Install Node.js'

- script: |
    npm install
    zip -r myExpressApp.zip
  displayName: 'npm install and build'

- publish: '$(System.DefaultWorkingDirectory)/myExpressApp.zip'
  artifact: 'myExpressApp'
  displayName: 'publish Artifact'

